service: serverless
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-2

functions:
  hello:
    handler: src/handler.hello

    events:
      - http:
          path: hello
          method: get