name: AWS lambda unit test
on: 
  push: 
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-

    - run: npm install

    - name: Unit test
      run: npm run test
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    if: success()
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - run: npm ci

      - name: connect to AWS lambda
        uses: serverless/github-action@master
        with:
          args: deploy
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_CREDENTIAL_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_CREDENTIAL_SECRET}}
