name: AWS lambda unit test
on: 
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - name: Unit test
      run: npm run test
    
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: test-results/**/*.xml

#   deploy:
#     name: Deploy to AWS lambda
#     runs-on: ubuntu-latest
#     # needs: [ build ]
#     steps:
#       - name: install serverless globally
#         run: npm install -g serverless
            
#       - name: connect to AWS lambda
#         run: serverless config credentials -o --provider aws --key ${{secrets.AWS_CREDENTIAL_KEY}} --secret ${{secrets.AWS_CREDENTIAL_SECRET}}
        

        
