name: AWS lambda unit test
on: 
  push: 
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-

    - run: npm install

    - name: Unit test
      run: npm run test
    
    # - name: echo if success
    #   if: success()
    #   run: echo "I success the code!"

    # - name: echo if fail
    #   if: failure()
    #   run: echo "I fail the code!"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps: 
    # - name: install serverless globally
    #   run: npm install -g serverless
          
    # - name: connect to AWS lambda
    #   run: serverless config credentials -o --provider aws --key ${{secrets.AWS_CREDENTIAL_KEY}} --secret ${{secrets.AWS_CREDENTIAL_SECRET}}
        
